name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - 'test/**-rc*'

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo "tag=$(echo ${GITHUB_REF#refs/*/} | cut -d '/' -f 1)" >> $GITHUB_OUTPUT
      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.tag }} 
      
