name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - 'test/**-rc*'

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"
      - name: Test
        run: |
          echo $RELEASE_VERSION
