name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - 'test/**-rc*'

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo 'tag=${GITHUB_REF#refs/*/}' >> $GITHUB_OUTPUT
      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.tag }} | cut -d '/' -f 1
      
