name: Publish in GitHub Package Registry

on:  
  push:
    tags:
      - 'test/**-rc*'

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello World"
      - name: Set env
        run: echo "TAG_GITHUB=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo "MODULE=$(echo $TAG_GITHUB | sed -nE 's/.*\/(.*)\/(.*)/\1/p')" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $MODULE
